### ISSUE TITLE
invalid decimal literal for wifi stick serial number.

### ISSUE THREAD

**Issue by wawyed** [NosIreland/solismon3#6]
My wifi stick serial number is hexadecimal, so I get this error

2023-01-26 20:01:06 SyntaxError: invalid decimal literal
2023-01-26 20:02:06 Traceback (most recent call last):
2023-01-26 20:02:06   File "/solismon3/./main.py", line 2, in <module>
2023-01-26 20:02:06     import config.config as config
2023-01-26 20:02:06   File "/solismon3/config/config.py", line 1
2023-01-26 20:02:06     INVERTER_SERIAL = XXXXXXXXXX   # WiFi stick serial number
2023-01-26 20:02:06                               ^
2023-01-26 20:02:06 SyntaxError: invalid decimal literal

**Comment by wawyed** [comment]
NVM I just saw that my wifi stick is not supported...
